"""add project creator foreign key

Revision ID: e147152c1727
Revises: ff68a8fb2f10
Create Date: 2026-08-26 15:13:31.930961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e147152c1727'
down_revision: Union[str, Sequence[str], None] = 'ff68a8fb2f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    # ### end Alembic commands ###
